version: 2.1

# See: https://circleci.com/docs/orb-intro/
orbs:
  # See: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@7.1.0

# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-test:
    jobs:
      - node/test:
          # https://circleci.com/developer/images/image/cimg/node
          executor: node/default
          pkg-manager: pnpm
